In [1]:
import cv2
import numpy as np



In [2]:
img = cv2.imread('Modi.jpg',1)
print(img)


[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [3]:
img.shape

(1358, 1500, 3)

## Original Modi Image

In [4]:
cv2.imshow('PM',img)
cv2.waitKey(2000)
cv2.destroyAllWindows()

## Resized Modi b/w Image

In [5]:
img=cv2.imread('Modi.jpg')
resized_image=cv2.resize(img,(500,500))
gray = cv2.cvtColor(resized_image,cv2.COLOR_BGR2GRAY)
cv2.imshow('Modi Image', gray)
cv2.waitKey(2000)
cv2.destroyAllWindows()

## Resized Modi color image

In [6]:
img=cv2.imread('Modi.jpg')
resized_image=cv2.resize(img,(500,500))
gray = cv2.cvtColor(resized_image,cv2.COLOR_BGR2GRAY)
cv2.imshow('Modi Image', resized_image)
cv2.waitKey(2000)
cv2.destroyAllWindows()

In [7]:
img.shape[0]*0.5

679.0

In [8]:
img.shape[1]*0.5

750.0

In [9]:
face_classifier = cv2.CascadeClassifier('haarcascade_frontalface_default[1].xml')
print(face_classifier)

< cv2.CascadeClassifier 0000025188C149D0>


In [11]:
image = cv2.imread('Modi.jpg')
image = cv2.resize(image,(500,500))
gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
faces = face_classifier.detectMultiScale(image , 1.05 , 5)


In [12]:
print(faces)

[[205  79 217 217]]


## Modi Face Detection b/w

In [13]:
if faces is ():
    print('No faces found')
    
for (x,y,w,h) in faces :
    cv2.rectangle(gray,(x,y),(x+w,y+h),(0,255,100),1)
cv2.imshow('Face Detection',gray)
cv2.waitKey(2000)
cv2.destroyAllWindows()

<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\choll\AppData\Local\Temp\ipykernel_29756\2519581795.py:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


## Modi Face Detection color

In [14]:
if faces is ():
    print('No faces found')
    
for (x,y,w,h) in faces :
    cv2.rectangle(image,(x,y),(x+w,y+h),(0,255,100),1)
cv2.imshow('Face Detection',image)
cv2.waitKey(2000)
cv2.destroyAllWindows()

<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\choll\AppData\Local\Temp\ipykernel_29756\2901261343.py:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


In [15]:
face_classifier = cv2.CascadeClassifier('haarcascade_frontalface_default[1].xml')
eye_classifier = cv2.CascadeClassifier('haarcascade_eye.xml')

## Modi Face and eye detection color

In [16]:
img = cv2.imread('Modi.jpg')
resized_image =cv2.resize(img,(500,500))
gray = cv2.cvtColor(resized_image,cv2.COLOR_BGR2GRAY)

faces = face_classifier.detectMultiScale(resized_image,1.3,5)

if faces is ():
    print('no faces found')
    
for (x,y,w,h) in faces:
    cv2.rectangle(resized_image,(x,y),(x+w,y+h),(255,0,0),2)
    roi_gray = gray[y:y+h,x:x+w]
    roi_color = resized_image[y:y+h,x:x+w]
    eyes = eye_classifier.detectMultiScale(roi_color)
    for (ex,ey,ew,eh) in eyes:
        cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,0,255),2)
        
cv2.imshow('img',resized_image)
cv2.waitKey(2000)
cv2.destroyAllWindows()

<>:7: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:7: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\choll\AppData\Local\Temp\ipykernel_29756\720439444.py:7: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


## Modi Face and eye detection b/w

In [17]:
img = cv2.imread('Modi.jpg')
resized_image =cv2.resize(img,(500,500))
gray = cv2.cvtColor(resized_image,cv2.COLOR_BGR2GRAY)

faces = face_classifier.detectMultiScale(gray, 1.3, 5)

if faces is ():
    print('no faces found')
    
for (x,y,w,h) in faces:
    cv2.rectangle(gray,(x,y),(x+w,y+h),(0,255,0),2)
    roi_gray = gray[y:y+h,x:x+w]
    roi_color = resized_image[y:y+h,x:x+w]
    eyes = eye_classifier.detectMultiScale(roi_gray)
    for (ex,ey,ew,eh) in eyes:
        cv2.rectangle(roi_gray,(ex,ey),(ex+ew,ey+eh),(255,0,0),2)
        
cv2.imshow('img',gray)
cv2.waitKey(2000)
cv2.destroyAllWindows()

<>:7: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:7: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\choll\AppData\Local\Temp\ipykernel_29756\203300042.py:7: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():
